// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: eth/tracers/native/proto/gas_dimension.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GasesByDimension represents the gas consumption for each dimension
type GasesByDimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the total gas cost for the opcode, across all dimensions.
	OneDimensionalGasCost uint64 `protobuf:"varint,1,opt,name=one_dimensional_gas_cost,json=oneDimensionalGasCost,proto3" json:"one_dimensional_gas_cost,omitempty"`
	// how much of the gas was used for computation or local memory access, stack operations, etc.
	Computation uint64 `protobuf:"varint,2,opt,name=computation,proto3" json:"computation,omitempty"`
	// how much of the gas was used for state access, like reading or writing to the state.
	StateAccess uint64 `protobuf:"varint,3,opt,name=state_access,json=stateAccess,proto3" json:"state_access,omitempty"`
	// how much of the gas was used for state growth, like creating new contracts or storage slots.
	StateGrowth uint64 `protobuf:"varint,4,opt,name=state_growth,json=stateGrowth,proto3" json:"state_growth,omitempty"`
	// how much of the gas was used for history growth, like writing to the history (event logs)
	HistoryGrowth uint64 `protobuf:"varint,5,opt,name=history_growth,json=historyGrowth,proto3" json:"history_growth,omitempty"`
	// how much gas was refunded for removing state, only applicable to SSTORE opcodes to zero.
	StateGrowthRefund int64 `protobuf:"varint,6,opt,name=state_growth_refund,json=stateGrowthRefund,proto3" json:"state_growth_refund,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GasesByDimension) Reset() {
	*x = GasesByDimension{}
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasesByDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasesByDimension) ProtoMessage() {}

func (x *GasesByDimension) ProtoReflect() protoreflect.Message {
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasesByDimension.ProtoReflect.Descriptor instead.
func (*GasesByDimension) Descriptor() ([]byte, []int) {
	return file_eth_tracers_native_proto_gas_dimension_proto_rawDescGZIP(), []int{0}
}

func (x *GasesByDimension) GetOneDimensionalGasCost() uint64 {
	if x != nil {
		return x.OneDimensionalGasCost
	}
	return 0
}

func (x *GasesByDimension) GetComputation() uint64 {
	if x != nil {
		return x.Computation
	}
	return 0
}

func (x *GasesByDimension) GetStateAccess() uint64 {
	if x != nil {
		return x.StateAccess
	}
	return 0
}

func (x *GasesByDimension) GetStateGrowth() uint64 {
	if x != nil {
		return x.StateGrowth
	}
	return 0
}

func (x *GasesByDimension) GetHistoryGrowth() uint64 {
	if x != nil {
		return x.HistoryGrowth
	}
	return 0
}

func (x *GasesByDimension) GetStateGrowthRefund() int64 {
	if x != nil {
		return x.StateGrowthRefund
	}
	return 0
}

// TxGasDimensionByOpcodeExecutionResult represents the execution result
type TxGasDimensionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the total amount of gas used in the transaction
	GasUsed uint64 `protobuf:"varint,1,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// the gas paid to post the compressed transaction to the L1 chain
	GasUsedL1 uint64 `protobuf:"varint,2,opt,name=gas_used_l1,json=gasUsedL1,proto3" json:"gas_used_l1,omitempty"`
	// the gas paid to execute the transaction on the L2 chain
	GasUsedL2 uint64 `protobuf:"varint,3,opt,name=gas_used_l2,json=gasUsedL2,proto3" json:"gas_used_l2,omitempty"`
	// the intrinsic gas of the transaction, the static cost + calldata bytes cost
	IntrinsicGas uint64 `protobuf:"varint,4,opt,name=intrinsic_gas,json=intrinsicGas,proto3" json:"intrinsic_gas,omitempty"`
	// the sum of the gas consumption categorized by dimension for that transaction
	Dimensions *GasesByDimension `protobuf:"bytes,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// the adjusted gas refund amount after EIP-3529
	AdjustedRefund *uint64 `protobuf:"varint,6,opt,name=adjusted_refund,json=adjustedRefund,proto3,oneof" json:"adjusted_refund,omitempty"`
	// the adjustment to the gas used for the root of the transaction if it is a precompile
	RootIsPrecompileAdjustment *uint64 `protobuf:"varint,7,opt,name=root_is_precompile_adjustment,json=rootIsPrecompileAdjustment,proto3,oneof" json:"root_is_precompile_adjustment,omitempty"`
	// the adjustment to the gas used for the root of the transaction if it is a stylus contract
	RootIsStylusAdjustment *uint64 `protobuf:"varint,8,opt,name=root_is_stylus_adjustment,json=rootIsStylusAdjustment,proto3,oneof" json:"root_is_stylus_adjustment,omitempty"`
	// whether the transaction broke the rules of the VM and was rejected
	Failed *bool `protobuf:"varint,9,opt,name=failed,proto3,oneof" json:"failed,omitempty"`
	// the status of the transaction, for a valid transaction that followed the rules,
	// but could have still failed for reasons inside the rules, like reverts, out of gas, etc.
	TransactionReverted *bool `protobuf:"varint,10,opt,name=transaction_reverted,json=transactionReverted,proto3,oneof" json:"transaction_reverted,omitempty"`
	// the hash of the transaction
	TxHash        string `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxGasDimensionResult) Reset() {
	*x = TxGasDimensionResult{}
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxGasDimensionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxGasDimensionResult) ProtoMessage() {}

func (x *TxGasDimensionResult) ProtoReflect() protoreflect.Message {
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxGasDimensionResult.ProtoReflect.Descriptor instead.
func (*TxGasDimensionResult) Descriptor() ([]byte, []int) {
	return file_eth_tracers_native_proto_gas_dimension_proto_rawDescGZIP(), []int{1}
}

func (x *TxGasDimensionResult) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *TxGasDimensionResult) GetGasUsedL1() uint64 {
	if x != nil {
		return x.GasUsedL1
	}
	return 0
}

func (x *TxGasDimensionResult) GetGasUsedL2() uint64 {
	if x != nil {
		return x.GasUsedL2
	}
	return 0
}

func (x *TxGasDimensionResult) GetIntrinsicGas() uint64 {
	if x != nil {
		return x.IntrinsicGas
	}
	return 0
}

func (x *TxGasDimensionResult) GetDimensions() *GasesByDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TxGasDimensionResult) GetAdjustedRefund() uint64 {
	if x != nil && x.AdjustedRefund != nil {
		return *x.AdjustedRefund
	}
	return 0
}

func (x *TxGasDimensionResult) GetRootIsPrecompileAdjustment() uint64 {
	if x != nil && x.RootIsPrecompileAdjustment != nil {
		return *x.RootIsPrecompileAdjustment
	}
	return 0
}

func (x *TxGasDimensionResult) GetRootIsStylusAdjustment() uint64 {
	if x != nil && x.RootIsStylusAdjustment != nil {
		return *x.RootIsStylusAdjustment
	}
	return 0
}

func (x *TxGasDimensionResult) GetFailed() bool {
	if x != nil && x.Failed != nil {
		return *x.Failed
	}
	return false
}

func (x *TxGasDimensionResult) GetTransactionReverted() bool {
	if x != nil && x.TransactionReverted != nil {
		return *x.TransactionReverted
	}
	return false
}

func (x *TxGasDimensionResult) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type BlockInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the timestamp of the block
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// how long it took to insert the block
	InsertDurationNanoseconds uint64 `protobuf:"varint,2,opt,name=insert_duration_nanoseconds,json=insertDurationNanoseconds,proto3" json:"insert_duration_nanoseconds,omitempty"`
	// block base fee
	BaseFee       uint64 `protobuf:"varint,3,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_eth_tracers_native_proto_gas_dimension_proto_rawDescGZIP(), []int{2}
}

func (x *BlockInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockInfo) GetInsertDurationNanoseconds() uint64 {
	if x != nil {
		return x.InsertDurationNanoseconds
	}
	return 0
}

func (x *BlockInfo) GetBaseFee() uint64 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

var File_eth_tracers_native_proto_gas_dimension_proto protoreflect.FileDescriptor

const file_eth_tracers_native_proto_gas_dimension_proto_rawDesc = "" +
	"\n" +
	",eth/tracers/native/proto/gas_dimension.proto\x12\x18eth.tracers.native.proto\"\x8a\x02\n" +
	"\x10GasesByDimension\x127\n" +
	"\x18one_dimensional_gas_cost\x18\x01 \x01(\x04R\x15oneDimensionalGasCost\x12 \n" +
	"\vcomputation\x18\x02 \x01(\x04R\vcomputation\x12!\n" +
	"\fstate_access\x18\x03 \x01(\x04R\vstateAccess\x12!\n" +
	"\fstate_growth\x18\x04 \x01(\x04R\vstateGrowth\x12%\n" +
	"\x0ehistory_growth\x18\x05 \x01(\x04R\rhistoryGrowth\x12.\n" +
	"\x13state_growth_refund\x18\x06 \x01(\x03R\x11stateGrowthRefund\"\xfe\x04\n" +
	"\x14TxGasDimensionResult\x12\x19\n" +
	"\bgas_used\x18\x01 \x01(\x04R\agasUsed\x12\x1e\n" +
	"\vgas_used_l1\x18\x02 \x01(\x04R\tgasUsedL1\x12\x1e\n" +
	"\vgas_used_l2\x18\x03 \x01(\x04R\tgasUsedL2\x12#\n" +
	"\rintrinsic_gas\x18\x04 \x01(\x04R\fintrinsicGas\x12J\n" +
	"\n" +
	"dimensions\x18\x05 \x01(\v2*.eth.tracers.native.proto.GasesByDimensionR\n" +
	"dimensions\x12,\n" +
	"\x0fadjusted_refund\x18\x06 \x01(\x04H\x00R\x0eadjustedRefund\x88\x01\x01\x12F\n" +
	"\x1droot_is_precompile_adjustment\x18\a \x01(\x04H\x01R\x1arootIsPrecompileAdjustment\x88\x01\x01\x12>\n" +
	"\x19root_is_stylus_adjustment\x18\b \x01(\x04H\x02R\x16rootIsStylusAdjustment\x88\x01\x01\x12\x1b\n" +
	"\x06failed\x18\t \x01(\bH\x03R\x06failed\x88\x01\x01\x126\n" +
	"\x14transaction_reverted\x18\n" +
	" \x01(\bH\x04R\x13transactionReverted\x88\x01\x01\x12\x17\n" +
	"\atx_hash\x18\v \x01(\tR\x06txHashB\x12\n" +
	"\x10_adjusted_refundB \n" +
	"\x1e_root_is_precompile_adjustmentB\x1c\n" +
	"\x1a_root_is_stylus_adjustmentB\t\n" +
	"\a_failedB\x17\n" +
	"\x15_transaction_reverted\"\x84\x01\n" +
	"\tBlockInfo\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12>\n" +
	"\x1binsert_duration_nanoseconds\x18\x02 \x01(\x04R\x19insertDurationNanoseconds\x12\x19\n" +
	"\bbase_fee\x18\x03 \x01(\x04R\abaseFeeB:Z8github.com/ethereum/go-ethereum/eth/tracers/native/protob\x06proto3"

var (
	file_eth_tracers_native_proto_gas_dimension_proto_rawDescOnce sync.Once
	file_eth_tracers_native_proto_gas_dimension_proto_rawDescData []byte
)

func file_eth_tracers_native_proto_gas_dimension_proto_rawDescGZIP() []byte {
	file_eth_tracers_native_proto_gas_dimension_proto_rawDescOnce.Do(func() {
		file_eth_tracers_native_proto_gas_dimension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eth_tracers_native_proto_gas_dimension_proto_rawDesc), len(file_eth_tracers_native_proto_gas_dimension_proto_rawDesc)))
	})
	return file_eth_tracers_native_proto_gas_dimension_proto_rawDescData
}

var file_eth_tracers_native_proto_gas_dimension_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eth_tracers_native_proto_gas_dimension_proto_goTypes = []any{
	(*GasesByDimension)(nil),     // 0: eth.tracers.native.proto.GasesByDimension
	(*TxGasDimensionResult)(nil), // 1: eth.tracers.native.proto.TxGasDimensionResult
	(*BlockInfo)(nil),            // 2: eth.tracers.native.proto.BlockInfo
}
var file_eth_tracers_native_proto_gas_dimension_proto_depIdxs = []int32{
	0, // 0: eth.tracers.native.proto.TxGasDimensionResult.dimensions:type_name -> eth.tracers.native.proto.GasesByDimension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eth_tracers_native_proto_gas_dimension_proto_init() }
func file_eth_tracers_native_proto_gas_dimension_proto_init() {
	if File_eth_tracers_native_proto_gas_dimension_proto != nil {
		return
	}
	file_eth_tracers_native_proto_gas_dimension_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eth_tracers_native_proto_gas_dimension_proto_rawDesc), len(file_eth_tracers_native_proto_gas_dimension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eth_tracers_native_proto_gas_dimension_proto_goTypes,
		DependencyIndexes: file_eth_tracers_native_proto_gas_dimension_proto_depIdxs,
		MessageInfos:      file_eth_tracers_native_proto_gas_dimension_proto_msgTypes,
	}.Build()
	File_eth_tracers_native_proto_gas_dimension_proto = out.File
	file_eth_tracers_native_proto_gas_dimension_proto_goTypes = nil
	file_eth_tracers_native_proto_gas_dimension_proto_depIdxs = nil
}
