# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eth/tracers/native/proto/gas_dimension.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'eth/tracers/native/proto/gas_dimension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,eth/tracers/native/proto/gas_dimension.proto\x12\x18\x65th.tracers.native.proto\"\xaa\x01\n\x10GasesByDimension\x12 \n\x18one_dimensional_gas_cost\x18\x01 \x01(\x04\x12\x13\n\x0b\x63omputation\x18\x02 \x01(\x04\x12\x14\n\x0cstate_access\x18\x03 \x01(\x04\x12\x14\n\x0cstate_growth\x18\x04 \x01(\x04\x12\x16\n\x0ehistory_growth\x18\x05 \x01(\x04\x12\x1b\n\x13state_growth_refund\x18\x06 \x01(\x03\"\xf2\x03\n\x14TxGasDimensionResult\x12\x10\n\x08gas_used\x18\x01 \x01(\x04\x12\x13\n\x0bgas_used_l1\x18\x02 \x01(\x04\x12\x13\n\x0bgas_used_l2\x18\x03 \x01(\x04\x12\x15\n\rintrinsic_gas\x18\x04 \x01(\x04\x12>\n\ndimensions\x18\x05 \x01(\x0b\x32*.eth.tracers.native.proto.GasesByDimension\x12\x1c\n\x0f\x61\x64justed_refund\x18\x06 \x01(\x04H\x00\x88\x01\x01\x12*\n\x1droot_is_precompile_adjustment\x18\x07 \x01(\x04H\x01\x88\x01\x01\x12&\n\x19root_is_stylus_adjustment\x18\x08 \x01(\x04H\x02\x88\x01\x01\x12\x13\n\x06\x66\x61iled\x18\t \x01(\x08H\x03\x88\x01\x01\x12!\n\x14transaction_reverted\x18\n \x01(\x08H\x04\x88\x01\x01\x12\x0f\n\x07tx_hash\x18\x0b \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x0c \x01(\x04\x42\x12\n\x10_adjusted_refundB \n\x1e_root_is_precompile_adjustmentB\x1c\n\x1a_root_is_stylus_adjustmentB\t\n\x07_failedB\x17\n\x15_transaction_reverted\"\\\n\x19TxGasDimensionResultBatch\x12?\n\x07results\x18\x01 \x03(\x0b\x32..eth.tracers.native.proto.TxGasDimensionResult\"k\n\tBlockInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12#\n\x1binsert_duration_nanoseconds\x18\x02 \x01(\x04\x12\x10\n\x08\x62\x61se_fee\x18\x03 \x01(\x04\x12\x14\n\x0c\x62lock_number\x18\x04 \x01(\x04\"E\n\x0e\x42lockInfoBatch\x12\x33\n\x06\x62locks\x18\x01 \x03(\x0b\x32#.eth.tracers.native.proto.BlockInfoB:Z8github.com/ethereum/go-ethereum/eth/tracers/native/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eth.tracers.native.proto.gas_dimension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/ethereum/go-ethereum/eth/tracers/native/proto'
  _globals['_GASESBYDIMENSION']._serialized_start=75
  _globals['_GASESBYDIMENSION']._serialized_end=245
  _globals['_TXGASDIMENSIONRESULT']._serialized_start=248
  _globals['_TXGASDIMENSIONRESULT']._serialized_end=746
  _globals['_TXGASDIMENSIONRESULTBATCH']._serialized_start=748
  _globals['_TXGASDIMENSIONRESULTBATCH']._serialized_end=840
  _globals['_BLOCKINFO']._serialized_start=842
  _globals['_BLOCKINFO']._serialized_end=949
  _globals['_BLOCKINFOBATCH']._serialized_start=951
  _globals['_BLOCKINFOBATCH']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
