// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: eth/tracers/native/proto/gas_dimension_by_opcode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GasesByDimension represents the gas consumption for each dimension
type GasesByDimension struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OneDimensionalGasCost uint64                 `protobuf:"varint,1,opt,name=one_dimensional_gas_cost,json=oneDimensionalGasCost,proto3" json:"one_dimensional_gas_cost,omitempty"`
	Computation           uint64                 `protobuf:"varint,2,opt,name=computation,proto3" json:"computation,omitempty"`
	StateAccess           uint64                 `protobuf:"varint,3,opt,name=state_access,json=stateAccess,proto3" json:"state_access,omitempty"`
	StateGrowth           uint64                 `protobuf:"varint,4,opt,name=state_growth,json=stateGrowth,proto3" json:"state_growth,omitempty"`
	HistoryGrowth         uint64                 `protobuf:"varint,5,opt,name=history_growth,json=historyGrowth,proto3" json:"history_growth,omitempty"`
	StateGrowthRefund     int64                  `protobuf:"varint,6,opt,name=state_growth_refund,json=stateGrowthRefund,proto3" json:"state_growth_refund,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GasesByDimension) Reset() {
	*x = GasesByDimension{}
	mi := &file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasesByDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasesByDimension) ProtoMessage() {}

func (x *GasesByDimension) ProtoReflect() protoreflect.Message {
	mi := &file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasesByDimension.ProtoReflect.Descriptor instead.
func (*GasesByDimension) Descriptor() ([]byte, []int) {
	return file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescGZIP(), []int{0}
}

func (x *GasesByDimension) GetOneDimensionalGasCost() uint64 {
	if x != nil {
		return x.OneDimensionalGasCost
	}
	return 0
}

func (x *GasesByDimension) GetComputation() uint64 {
	if x != nil {
		return x.Computation
	}
	return 0
}

func (x *GasesByDimension) GetStateAccess() uint64 {
	if x != nil {
		return x.StateAccess
	}
	return 0
}

func (x *GasesByDimension) GetStateGrowth() uint64 {
	if x != nil {
		return x.StateGrowth
	}
	return 0
}

func (x *GasesByDimension) GetHistoryGrowth() uint64 {
	if x != nil {
		return x.HistoryGrowth
	}
	return 0
}

func (x *GasesByDimension) GetStateGrowthRefund() int64 {
	if x != nil {
		return x.StateGrowthRefund
	}
	return 0
}

// TxGasDimensionByOpcodeExecutionResult represents the execution result
type TxGasDimensionByOpcodeExecutionResult struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Gas            uint64                       `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	Failed         bool                         `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Dimensions     map[uint32]*GasesByDimension `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TxHash         string                       `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockTimestamp uint64                       `protobuf:"varint,5,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	BlockNumber    string                       `protobuf:"bytes,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"` // Using string to represent big.Int
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TxGasDimensionByOpcodeExecutionResult) Reset() {
	*x = TxGasDimensionByOpcodeExecutionResult{}
	mi := &file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxGasDimensionByOpcodeExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxGasDimensionByOpcodeExecutionResult) ProtoMessage() {}

func (x *TxGasDimensionByOpcodeExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxGasDimensionByOpcodeExecutionResult.ProtoReflect.Descriptor instead.
func (*TxGasDimensionByOpcodeExecutionResult) Descriptor() ([]byte, []int) {
	return file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescGZIP(), []int{1}
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetDimensions() map[uint32]*GasesByDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

func (x *TxGasDimensionByOpcodeExecutionResult) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

var File_eth_tracers_native_proto_gas_dimension_by_opcode_proto protoreflect.FileDescriptor

const file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDesc = "" +
	"\n" +
	"6eth/tracers/native/proto/gas_dimension_by_opcode.proto\x12\x18eth.tracers.native.proto\"\x8a\x02\n" +
	"\x10GasesByDimension\x127\n" +
	"\x18one_dimensional_gas_cost\x18\x01 \x01(\x04R\x15oneDimensionalGasCost\x12 \n" +
	"\vcomputation\x18\x02 \x01(\x04R\vcomputation\x12!\n" +
	"\fstate_access\x18\x03 \x01(\x04R\vstateAccess\x12!\n" +
	"\fstate_growth\x18\x04 \x01(\x04R\vstateGrowth\x12%\n" +
	"\x0ehistory_growth\x18\x05 \x01(\x04R\rhistoryGrowth\x12.\n" +
	"\x13state_growth_refund\x18\x06 \x01(\x03R\x11stateGrowthRefund\"\x92\x03\n" +
	"%TxGasDimensionByOpcodeExecutionResult\x12\x10\n" +
	"\x03gas\x18\x01 \x01(\x04R\x03gas\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\x12o\n" +
	"\n" +
	"dimensions\x18\x03 \x03(\v2O.eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult.DimensionsEntryR\n" +
	"dimensions\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12'\n" +
	"\x0fblock_timestamp\x18\x05 \x01(\x04R\x0eblockTimestamp\x12!\n" +
	"\fblock_number\x18\x06 \x01(\tR\vblockNumber\x1ai\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.eth.tracers.native.proto.GasesByDimensionR\x05value:\x028\x01B:Z8github.com/ethereum/go-ethereum/eth/tracers/native/protob\x06proto3"

var (
	file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescOnce sync.Once
	file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescData []byte
)

func file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescGZIP() []byte {
	file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescOnce.Do(func() {
		file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDesc), len(file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDesc)))
	})
	return file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDescData
}

var file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_goTypes = []any{
	(*GasesByDimension)(nil),                      // 0: eth.tracers.native.proto.GasesByDimension
	(*TxGasDimensionByOpcodeExecutionResult)(nil), // 1: eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult
	nil, // 2: eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult.DimensionsEntry
}
var file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_depIdxs = []int32{
	2, // 0: eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult.dimensions:type_name -> eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult.DimensionsEntry
	0, // 1: eth.tracers.native.proto.TxGasDimensionByOpcodeExecutionResult.DimensionsEntry.value:type_name -> eth.tracers.native.proto.GasesByDimension
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_init() }
func file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_init() {
	if File_eth_tracers_native_proto_gas_dimension_by_opcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDesc), len(file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_goTypes,
		DependencyIndexes: file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_depIdxs,
		MessageInfos:      file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_msgTypes,
	}.Build()
	File_eth_tracers_native_proto_gas_dimension_by_opcode_proto = out.File
	file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_goTypes = nil
	file_eth_tracers_native_proto_gas_dimension_by_opcode_proto_depIdxs = nil
}
