// Code generated by "stringer -type=BalanceChangeReason -trimprefix=BalanceChange -output gen_balance_change_reason_stringer.go"; DO NOT EDIT.

package tracing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BalanceChangeUnspecified-0]
	_ = x[BalanceIncreaseRewardMineUncle-1]
	_ = x[BalanceIncreaseRewardMineBlock-2]
	_ = x[BalanceIncreaseWithdrawal-3]
	_ = x[BalanceIncreaseGenesisBalance-4]
	_ = x[BalanceIncreaseRewardTransactionFee-5]
	_ = x[BalanceDecreaseGasBuy-6]
	_ = x[BalanceIncreaseGasReturn-7]
	_ = x[BalanceIncreaseDaoContract-8]
	_ = x[BalanceDecreaseDaoAccount-9]
	_ = x[BalanceChangeTransfer-10]
	_ = x[BalanceChangeTouchAccount-11]
	_ = x[BalanceIncreaseSelfdestruct-12]
	_ = x[BalanceDecreaseSelfdestruct-13]
	_ = x[BalanceDecreaseSelfdestructBurn-14]
	_ = x[BalanceChangeRevert-15]
	_ = x[BalanceChangeDuringEVMExecution-128]
	_ = x[BalanceIncreaseDeposit-129]
	_ = x[BalanceDecreaseWithdrawToL1-130]
	_ = x[BalanceIncreaseL1PosterFee-131]
	_ = x[BalanceIncreaseInfraFee-132]
	_ = x[BalanceIncreaseNetworkFee-133]
	_ = x[BalanceChangeTransferInfraRefund-134]
	_ = x[BalanceChangeTransferNetworkRefund-135]
	_ = x[BalanceIncreasePrepaid-136]
	_ = x[BalanceDecreaseUndoRefund-137]
	_ = x[BalanceChangeEscrowTransfer-138]
	_ = x[BalanceChangeTransferBatchposterReward-139]
	_ = x[BalanceChangeTransferBatchposterRefund-140]
	_ = x[BalanceChangeTransferRetryableExcessRefund-141]
	_ = x[BalanceChangeTransferActivationFee-142]
	_ = x[BalanceChangeTransferActivationReimburse-143]
	_ = x[BalanceIncreaseMintNativeToken-144]
	_ = x[BalanceDecreaseBurnNativeToken-145]
}

const (
	_BalanceChangeReason_name_0 = "UnspecifiedBalanceIncreaseRewardMineUncleBalanceIncreaseRewardMineBlockBalanceIncreaseWithdrawalBalanceIncreaseGenesisBalanceBalanceIncreaseRewardTransactionFeeBalanceDecreaseGasBuyBalanceIncreaseGasReturnBalanceIncreaseDaoContractBalanceDecreaseDaoAccountTransferTouchAccountBalanceIncreaseSelfdestructBalanceDecreaseSelfdestructBalanceDecreaseSelfdestructBurnRevert"
	_BalanceChangeReason_name_1 = "DuringEVMExecutionBalanceIncreaseDepositBalanceDecreaseWithdrawToL1BalanceIncreaseL1PosterFeeBalanceIncreaseInfraFeeBalanceIncreaseNetworkFeeTransferInfraRefundTransferNetworkRefundBalanceIncreasePrepaidBalanceDecreaseUndoRefundEscrowTransferTransferBatchposterRewardTransferBatchposterRefundTransferRetryableExcessRefundTransferActivationFeeTransferActivationReimburseBalanceIncreaseMintNativeTokenBalanceDecreaseBurnNativeToken"
)

var (
	_BalanceChangeReason_index_0 = [...]uint16{0, 11, 41, 71, 96, 125, 160, 181, 205, 231, 256, 264, 276, 303, 330, 361, 367}
	_BalanceChangeReason_index_1 = [...]uint16{0, 18, 40, 67, 93, 116, 141, 160, 181, 203, 228, 242, 267, 292, 321, 342, 369, 399, 429}
)

func (i BalanceChangeReason) String() string {
	switch {
	case i <= 15:
		return _BalanceChangeReason_name_0[_BalanceChangeReason_index_0[i]:_BalanceChangeReason_index_0[i+1]]
	case 128 <= i && i <= 145:
		i -= 128
		return _BalanceChangeReason_name_1[_BalanceChangeReason_index_1[i]:_BalanceChangeReason_index_1[i+1]]
	default:
		return "BalanceChangeReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
