// Code generated by "stringer -type=ResourceKind -trimprefix=ResourceKind"; DO NOT EDIT.

package multigas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceKindUnknown-0]
	_ = x[ResourceKindComputation-1]
	_ = x[ResourceKindHistoryGrowth-2]
	_ = x[ResourceKindStorageAccess-3]
	_ = x[ResourceKindStorageGrowth-4]
	_ = x[ResourceKindSingleDim-5]
	_ = x[ResourceKindL2Calldata-6]
	_ = x[ResourceKindWasmComputation-7]
	_ = x[NumResourceKind-8]
}

const _ResourceKind_name = "UnknownComputationHistoryGrowthStorageAccessStorageGrowthSingleDimL2CalldataWasmComputationNumResourceKind"

var _ResourceKind_index = [...]uint8{0, 7, 18, 31, 44, 57, 66, 76, 91, 106}

func (i ResourceKind) String() string {
	if i >= ResourceKind(len(_ResourceKind_index)-1) {
		return "ResourceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceKind_name[_ResourceKind_index[i]:_ResourceKind_index[i+1]]
}
