// Code generated by "stringer -type=ResourceKind -trimprefix=ResourceKind"; DO NOT EDIT.

package multigas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceKindUnknown-0]
	_ = x[ResourceKindComputation-1]
	_ = x[ResourceKindHistoryGrowth-2]
	_ = x[ResourceKindStorageAccessRead-3]
	_ = x[ResourceKindStorageAccessWrite-4]
	_ = x[ResourceKindStorageGrowth-5]
	_ = x[ResourceKindL1Calldata-6]
	_ = x[ResourceKindL2Calldata-7]
	_ = x[ResourceKindWasmComputation-8]
	_ = x[NumResourceKind-9]
}

const _ResourceKind_name = "UnknownComputationHistoryGrowthStorageAccessReadStorageAccessWriteStorageGrowthL1CalldataL2CalldataWasmComputationNumResourceKind"

var _ResourceKind_index = [...]uint8{0, 7, 18, 31, 48, 66, 79, 89, 99, 114, 129}

func (i ResourceKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceKind_index)-1 {
		return "ResourceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceKind_name[_ResourceKind_index[idx]:_ResourceKind_index[idx+1]]
}
